# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
metadata:
  name: embeddingbinaries
spec:
  containers:
    - name: myworkload
      image: 111222333444.dkr.ecr.eu-west-1.amazonaws.com/falco:embeddedbinaries
      volumeMounts:
        - name: falco-config
          mountPath: "/data/falco.yaml"
          subPath: "falco.yaml"
          readOnly: true
        - name: falco-local-rules
          mountPath: "/data/falco_rules.local.yaml"
          subPath: "falco_rules.local.yaml"
          readOnly: true
  volumes:
  - name: falco-config
    configMap:
      name: falco-config
  - name: falco-local-rules
    configMap:
      name: falco-local-rules