FROM debian

RUN apt-get update && \
  apt-get install -y \
  curl

COPY --from=ollypom/pdig:latest /pdig /vendor/falco/bin/pdig
COPY ./myscript.sh  /vendor/falco/scripts/myscript.sh

CMD ["/vendor/falco/bin/pdig", "/bin/bash", "/vendor/falco/scripts/myscript.sh"]