FROM scratch

COPY --from=ollypom/pdig:latest /pdig /vendor/falco/bin/pdig
COPY --from=falcosecurity/falco:0.32.2-slim      /usr/bin/falco         /vendor/falco/bin/falco
COPY --from=falcosecurity/kilt-utilities:latest  /kilt/                 /vendor/falco/bin/
COPY --from=falcosecurity/falco:0.32.2-slim      /etc/falco/            /vendor/falco/etc/falco/

VOLUME ["/vendor/falco"]

CMD ["/vendor/falco/bin/waitforever"]
